title: y.tanaka
description: >
baseurl: ""
url: "https://yoshi-chanaka.github.io/"

author:
  name: y.tanaka
  email: ysk.tanaka98@gmail.com
  github: yoshi-chanaka

paginate: 3
paginate_path: page:num

sass:
  style: expanded

gems:
  - jekyll-paginate
  - jekyll-feed
